### ISSUE TITLE
mode all work unexpected

### ISSUE THREAD

**Issue by kien8995** [FreedomNodes/substore-tools#103]
```yaml
4VPN:
  subs:
    - '4VPN'
  countries:
    - 🇻🇳
    - 🇯🇵
  ports:
    - 443
  name: "{F} VPN4 {0#}"
  sorts:
    - "name:asc"
    - "flag:🇻🇳:first"

```
