### ISSUE TITLE
rename by flag

### ISSUE THREAD

**Issue by kien8995** [FreedomNodes/substore-tools#104]
```yaml
4VPN:
  subs:
    - '4VPN'
  countries:
    - 🇻🇳
    - 🇯🇵
  ports:
    - 443
  name: 🇻🇳 = XXXX XXX
        🇯🇵 = AAAA AAAA
  sorts:
    - "name:asc"
    - "flag:🇻🇳:first"

```
